apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  labels:
    app: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - name: cache
          image: varnish:stable
          command:
            - varnishd
            - -F
            - -f
            - /etc/varnish/varnish-cache-config.vcl
            - -a
            - 0.0.0.0:8080
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: varnish
              mountPath: /etc/varnish
      volumes:
        - name: varnish
          configMap:
            name: varnish-config
